/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AnnouncementId = bigint;
export interface AnnouncementPayload {
  'title' : string,
  'recipientGroup' : RecipientGroup,
  'message' : string,
}
export interface AnnouncementView {
  'id' : AnnouncementId,
  'title' : string,
  'recipientGroup' : RecipientGroup,
  'createdAt' : Timestamp,
  'createdBy' : string,
  'message' : string,
}
export interface AttendanceEntry {
  'status' : AttendanceStatus,
  'studentId' : Id,
}
export type AttendanceId = bigint;
export interface AttendanceRecord {
  'id' : AttendanceId,
  'status' : AttendanceStatus,
  'studentId' : Id,
  'date' : string,
  'markedAt' : Timestamp,
  'className' : string,
}
export interface AttendanceStats {
  'studentId' : Id,
  'presentDays' : bigint,
  'totalDays' : bigint,
  'absentDays' : bigint,
  'presentPercent' : number,
}
export type AttendanceStatus = { 'present' : null } |
  { 'absent' : null };
export type ExamId = bigint;
export interface ExamPayload {
  'totalMarks' : bigint,
  'subjects' : Array<string>,
  'date' : string,
  'name' : string,
}
export interface ExamView {
  'id' : ExamId,
  'totalMarks' : bigint,
  'subjects' : Array<string>,
  'date' : string,
  'name' : string,
  'createdAt' : Timestamp,
}
export type Grade = { 'a' : null } |
  { 'b' : null } |
  { 'c' : null } |
  { 'd' : null } |
  { 'f' : null } |
  { 'aPlus' : null } |
  { 'cPlus' : null } |
  { 'bPlus' : null };
export type Id = bigint;
export type ParentId = bigint;
export interface ParentPayload {
  'name' : string,
  'studentIds' : Array<Id>,
  'contactEmail' : string,
  'contactPhone' : string,
}
export interface ParentView {
  'id' : ParentId,
  'name' : string,
  'createdAt' : Timestamp,
  'studentIds' : Array<Id>,
  'contactEmail' : string,
  'contactPhone' : string,
}
export type RecipientGroup = { 'all' : null } |
  { 'students' : null } |
  { 'teachers' : null } |
  { 'parents' : null };
export interface ReportCard {
  'studentId' : Id,
  'subjects' : Array<SubjectMarkView>,
  'totalObtained' : bigint,
  'grade' : Grade,
  'examId' : ExamId,
  'totalPossible' : bigint,
  'examName' : string,
  'percentage' : number,
}
export type Role = { 'admin' : null } |
  { 'teacher' : null } |
  { 'student' : null } |
  { 'parent' : null };
export type StudentId = bigint;
export interface StudentPayload {
  'name' : string,
  'rollNumber' : string,
  'contactEmail' : string,
  'parentId' : [] | [Id],
  'className' : string,
  'contactPhone' : string,
}
export interface StudentView {
  'id' : StudentId,
  'name' : string,
  'createdAt' : Timestamp,
  'rollNumber' : string,
  'contactEmail' : string,
  'parentId' : [] | [Id],
  'className' : string,
  'contactPhone' : string,
}
export interface SubjectMarkEntry {
  'studentId' : Id,
  'subject' : string,
  'marksObtained' : bigint,
}
export interface SubjectMarkView {
  'totalMarks' : bigint,
  'subject' : string,
  'marksObtained' : bigint,
  'grade' : Grade,
}
export type TeacherId = bigint;
export interface TeacherPayload {
  'subjects' : Array<string>,
  'name' : string,
  'contactEmail' : string,
  'contactPhone' : string,
}
export interface TeacherView {
  'id' : TeacherId,
  'subjects' : Array<string>,
  'name' : string,
  'createdAt' : Timestamp,
  'contactEmail' : string,
  'contactPhone' : string,
}
export type Timestamp = bigint;
export type UserId = Principal;
export interface _SERVICE {
  'addParent' : ActorMethod<[ParentPayload], ParentId>,
  'addStudent' : ActorMethod<[StudentPayload], StudentId>,
  'addTeacher' : ActorMethod<[TeacherPayload], TeacherId>,
  'assignRole' : ActorMethod<[UserId, Role], undefined>,
  'createAnnouncement' : ActorMethod<[AnnouncementPayload], AnnouncementId>,
  'createExam' : ActorMethod<[ExamPayload], ExamId>,
  'deleteParent' : ActorMethod<[ParentId], boolean>,
  'deleteStudent' : ActorMethod<[StudentId], boolean>,
  'deleteTeacher' : ActorMethod<[TeacherId], boolean>,
  'enterMarks' : ActorMethod<[ExamId, Array<SubjectMarkEntry>], bigint>,
  'getAttendanceReport' : ActorMethod<
    [[] | [string], string, string],
    Array<AttendanceRecord>
  >,
  'getClassAttendance' : ActorMethod<[string, string], Array<AttendanceRecord>>,
  'getExam' : ActorMethod<[ExamId], [] | [ExamView]>,
  'getMyRole' : ActorMethod<[], [] | [Role]>,
  'getParent' : ActorMethod<[ParentId], [] | [ParentView]>,
  'getReportCard' : ActorMethod<[Id, ExamId], [] | [ReportCard]>,
  'getStudent' : ActorMethod<[StudentId], [] | [StudentView]>,
  'getStudentAttendance' : ActorMethod<[Id], Array<AttendanceRecord>>,
  'getStudentAttendanceStats' : ActorMethod<[Id], AttendanceStats>,
  'getTeacher' : ActorMethod<[TeacherId], [] | [TeacherView]>,
  'isAdminPrincipal' : ActorMethod<[UserId], boolean>,
  'listAnnouncements' : ActorMethod<[], Array<AnnouncementView>>,
  'listAnnouncementsByGroup' : ActorMethod<
    [RecipientGroup],
    Array<AnnouncementView>
  >,
  'listExams' : ActorMethod<[], Array<ExamView>>,
  'listParents' : ActorMethod<[], Array<ParentView>>,
  'listStudents' : ActorMethod<[], Array<StudentView>>,
  'listTeachers' : ActorMethod<[], Array<TeacherView>>,
  'markAttendance' : ActorMethod<
    [string, string, Array<AttendanceEntry>],
    bigint
  >,
  'registerSelf' : ActorMethod<[Role], undefined>,
  'searchParents' : ActorMethod<[string], Array<ParentView>>,
  'searchStudents' : ActorMethod<[string], Array<StudentView>>,
  'searchTeachers' : ActorMethod<[string], Array<TeacherView>>,
  'updateParent' : ActorMethod<[ParentId, ParentPayload], boolean>,
  'updateStudent' : ActorMethod<[StudentId, StudentPayload], boolean>,
  'updateTeacher' : ActorMethod<[TeacherId, TeacherPayload], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];