/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Id = IDL.Nat;
export const ParentPayload = IDL.Record({
  'name' : IDL.Text,
  'studentIds' : IDL.Vec(Id),
  'contactEmail' : IDL.Text,
  'contactPhone' : IDL.Text,
});
export const ParentId = IDL.Nat;
export const StudentPayload = IDL.Record({
  'name' : IDL.Text,
  'rollNumber' : IDL.Text,
  'contactEmail' : IDL.Text,
  'parentId' : IDL.Opt(Id),
  'className' : IDL.Text,
  'contactPhone' : IDL.Text,
});
export const StudentId = IDL.Nat;
export const TeacherPayload = IDL.Record({
  'subjects' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'contactEmail' : IDL.Text,
  'contactPhone' : IDL.Text,
});
export const TeacherId = IDL.Nat;
export const UserId = IDL.Principal;
export const Role = IDL.Variant({
  'admin' : IDL.Null,
  'teacher' : IDL.Null,
  'student' : IDL.Null,
  'parent' : IDL.Null,
});
export const RecipientGroup = IDL.Variant({
  'all' : IDL.Null,
  'students' : IDL.Null,
  'teachers' : IDL.Null,
  'parents' : IDL.Null,
});
export const AnnouncementPayload = IDL.Record({
  'title' : IDL.Text,
  'recipientGroup' : RecipientGroup,
  'message' : IDL.Text,
});
export const AnnouncementId = IDL.Nat;
export const ExamPayload = IDL.Record({
  'totalMarks' : IDL.Nat,
  'subjects' : IDL.Vec(IDL.Text),
  'date' : IDL.Text,
  'name' : IDL.Text,
});
export const ExamId = IDL.Nat;
export const SubjectMarkEntry = IDL.Record({
  'studentId' : Id,
  'subject' : IDL.Text,
  'marksObtained' : IDL.Nat,
});
export const AttendanceId = IDL.Nat;
export const AttendanceStatus = IDL.Variant({
  'present' : IDL.Null,
  'absent' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const AttendanceRecord = IDL.Record({
  'id' : AttendanceId,
  'status' : AttendanceStatus,
  'studentId' : Id,
  'date' : IDL.Text,
  'markedAt' : Timestamp,
  'className' : IDL.Text,
});
export const ExamView = IDL.Record({
  'id' : ExamId,
  'totalMarks' : IDL.Nat,
  'subjects' : IDL.Vec(IDL.Text),
  'date' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
});
export const ParentView = IDL.Record({
  'id' : ParentId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'studentIds' : IDL.Vec(Id),
  'contactEmail' : IDL.Text,
  'contactPhone' : IDL.Text,
});
export const Grade = IDL.Variant({
  'a' : IDL.Null,
  'b' : IDL.Null,
  'c' : IDL.Null,
  'd' : IDL.Null,
  'f' : IDL.Null,
  'aPlus' : IDL.Null,
  'cPlus' : IDL.Null,
  'bPlus' : IDL.Null,
});
export const SubjectMarkView = IDL.Record({
  'totalMarks' : IDL.Nat,
  'subject' : IDL.Text,
  'marksObtained' : IDL.Nat,
  'grade' : Grade,
});
export const ReportCard = IDL.Record({
  'studentId' : Id,
  'subjects' : IDL.Vec(SubjectMarkView),
  'totalObtained' : IDL.Nat,
  'grade' : Grade,
  'examId' : ExamId,
  'totalPossible' : IDL.Nat,
  'examName' : IDL.Text,
  'percentage' : IDL.Float64,
});
export const StudentView = IDL.Record({
  'id' : StudentId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'rollNumber' : IDL.Text,
  'contactEmail' : IDL.Text,
  'parentId' : IDL.Opt(Id),
  'className' : IDL.Text,
  'contactPhone' : IDL.Text,
});
export const AttendanceStats = IDL.Record({
  'studentId' : Id,
  'presentDays' : IDL.Nat,
  'totalDays' : IDL.Nat,
  'absentDays' : IDL.Nat,
  'presentPercent' : IDL.Float64,
});
export const TeacherView = IDL.Record({
  'id' : TeacherId,
  'subjects' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'contactEmail' : IDL.Text,
  'contactPhone' : IDL.Text,
});
export const AnnouncementView = IDL.Record({
  'id' : AnnouncementId,
  'title' : IDL.Text,
  'recipientGroup' : RecipientGroup,
  'createdAt' : Timestamp,
  'createdBy' : IDL.Text,
  'message' : IDL.Text,
});
export const AttendanceEntry = IDL.Record({
  'status' : AttendanceStatus,
  'studentId' : Id,
});

export const idlService = IDL.Service({
  'addParent' : IDL.Func([ParentPayload], [ParentId], []),
  'addStudent' : IDL.Func([StudentPayload], [StudentId], []),
  'addTeacher' : IDL.Func([TeacherPayload], [TeacherId], []),
  'assignRole' : IDL.Func([UserId, Role], [], []),
  'createAnnouncement' : IDL.Func([AnnouncementPayload], [AnnouncementId], []),
  'createExam' : IDL.Func([ExamPayload], [ExamId], []),
  'deleteParent' : IDL.Func([ParentId], [IDL.Bool], []),
  'deleteStudent' : IDL.Func([StudentId], [IDL.Bool], []),
  'deleteTeacher' : IDL.Func([TeacherId], [IDL.Bool], []),
  'enterMarks' : IDL.Func([ExamId, IDL.Vec(SubjectMarkEntry)], [IDL.Nat], []),
  'getAttendanceReport' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Text, IDL.Text],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getClassAttendance' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getExam' : IDL.Func([ExamId], [IDL.Opt(ExamView)], ['query']),
  'getMyRole' : IDL.Func([], [IDL.Opt(Role)], ['query']),
  'getParent' : IDL.Func([ParentId], [IDL.Opt(ParentView)], ['query']),
  'getReportCard' : IDL.Func([Id, ExamId], [IDL.Opt(ReportCard)], ['query']),
  'getStudent' : IDL.Func([StudentId], [IDL.Opt(StudentView)], ['query']),
  'getStudentAttendance' : IDL.Func(
      [Id],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getStudentAttendanceStats' : IDL.Func([Id], [AttendanceStats], ['query']),
  'getTeacher' : IDL.Func([TeacherId], [IDL.Opt(TeacherView)], ['query']),
  'isAdminPrincipal' : IDL.Func([UserId], [IDL.Bool], ['query']),
  'listAnnouncements' : IDL.Func([], [IDL.Vec(AnnouncementView)], ['query']),
  'listAnnouncementsByGroup' : IDL.Func(
      [RecipientGroup],
      [IDL.Vec(AnnouncementView)],
      ['query'],
    ),
  'listExams' : IDL.Func([], [IDL.Vec(ExamView)], ['query']),
  'listParents' : IDL.Func([], [IDL.Vec(ParentView)], ['query']),
  'listStudents' : IDL.Func([], [IDL.Vec(StudentView)], ['query']),
  'listTeachers' : IDL.Func([], [IDL.Vec(TeacherView)], ['query']),
  'markAttendance' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(AttendanceEntry)],
      [IDL.Nat],
      [],
    ),
  'registerSelf' : IDL.Func([Role], [], []),
  'searchParents' : IDL.Func([IDL.Text], [IDL.Vec(ParentView)], ['query']),
  'searchStudents' : IDL.Func([IDL.Text], [IDL.Vec(StudentView)], ['query']),
  'searchTeachers' : IDL.Func([IDL.Text], [IDL.Vec(TeacherView)], ['query']),
  'updateParent' : IDL.Func([ParentId, ParentPayload], [IDL.Bool], []),
  'updateStudent' : IDL.Func([StudentId, StudentPayload], [IDL.Bool], []),
  'updateTeacher' : IDL.Func([TeacherId, TeacherPayload], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Id = IDL.Nat;
  const ParentPayload = IDL.Record({
    'name' : IDL.Text,
    'studentIds' : IDL.Vec(Id),
    'contactEmail' : IDL.Text,
    'contactPhone' : IDL.Text,
  });
  const ParentId = IDL.Nat;
  const StudentPayload = IDL.Record({
    'name' : IDL.Text,
    'rollNumber' : IDL.Text,
    'contactEmail' : IDL.Text,
    'parentId' : IDL.Opt(Id),
    'className' : IDL.Text,
    'contactPhone' : IDL.Text,
  });
  const StudentId = IDL.Nat;
  const TeacherPayload = IDL.Record({
    'subjects' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'contactEmail' : IDL.Text,
    'contactPhone' : IDL.Text,
  });
  const TeacherId = IDL.Nat;
  const UserId = IDL.Principal;
  const Role = IDL.Variant({
    'admin' : IDL.Null,
    'teacher' : IDL.Null,
    'student' : IDL.Null,
    'parent' : IDL.Null,
  });
  const RecipientGroup = IDL.Variant({
    'all' : IDL.Null,
    'students' : IDL.Null,
    'teachers' : IDL.Null,
    'parents' : IDL.Null,
  });
  const AnnouncementPayload = IDL.Record({
    'title' : IDL.Text,
    'recipientGroup' : RecipientGroup,
    'message' : IDL.Text,
  });
  const AnnouncementId = IDL.Nat;
  const ExamPayload = IDL.Record({
    'totalMarks' : IDL.Nat,
    'subjects' : IDL.Vec(IDL.Text),
    'date' : IDL.Text,
    'name' : IDL.Text,
  });
  const ExamId = IDL.Nat;
  const SubjectMarkEntry = IDL.Record({
    'studentId' : Id,
    'subject' : IDL.Text,
    'marksObtained' : IDL.Nat,
  });
  const AttendanceId = IDL.Nat;
  const AttendanceStatus = IDL.Variant({
    'present' : IDL.Null,
    'absent' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const AttendanceRecord = IDL.Record({
    'id' : AttendanceId,
    'status' : AttendanceStatus,
    'studentId' : Id,
    'date' : IDL.Text,
    'markedAt' : Timestamp,
    'className' : IDL.Text,
  });
  const ExamView = IDL.Record({
    'id' : ExamId,
    'totalMarks' : IDL.Nat,
    'subjects' : IDL.Vec(IDL.Text),
    'date' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
  });
  const ParentView = IDL.Record({
    'id' : ParentId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'studentIds' : IDL.Vec(Id),
    'contactEmail' : IDL.Text,
    'contactPhone' : IDL.Text,
  });
  const Grade = IDL.Variant({
    'a' : IDL.Null,
    'b' : IDL.Null,
    'c' : IDL.Null,
    'd' : IDL.Null,
    'f' : IDL.Null,
    'aPlus' : IDL.Null,
    'cPlus' : IDL.Null,
    'bPlus' : IDL.Null,
  });
  const SubjectMarkView = IDL.Record({
    'totalMarks' : IDL.Nat,
    'subject' : IDL.Text,
    'marksObtained' : IDL.Nat,
    'grade' : Grade,
  });
  const ReportCard = IDL.Record({
    'studentId' : Id,
    'subjects' : IDL.Vec(SubjectMarkView),
    'totalObtained' : IDL.Nat,
    'grade' : Grade,
    'examId' : ExamId,
    'totalPossible' : IDL.Nat,
    'examName' : IDL.Text,
    'percentage' : IDL.Float64,
  });
  const StudentView = IDL.Record({
    'id' : StudentId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'rollNumber' : IDL.Text,
    'contactEmail' : IDL.Text,
    'parentId' : IDL.Opt(Id),
    'className' : IDL.Text,
    'contactPhone' : IDL.Text,
  });
  const AttendanceStats = IDL.Record({
    'studentId' : Id,
    'presentDays' : IDL.Nat,
    'totalDays' : IDL.Nat,
    'absentDays' : IDL.Nat,
    'presentPercent' : IDL.Float64,
  });
  const TeacherView = IDL.Record({
    'id' : TeacherId,
    'subjects' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'contactEmail' : IDL.Text,
    'contactPhone' : IDL.Text,
  });
  const AnnouncementView = IDL.Record({
    'id' : AnnouncementId,
    'title' : IDL.Text,
    'recipientGroup' : RecipientGroup,
    'createdAt' : Timestamp,
    'createdBy' : IDL.Text,
    'message' : IDL.Text,
  });
  const AttendanceEntry = IDL.Record({
    'status' : AttendanceStatus,
    'studentId' : Id,
  });
  
  return IDL.Service({
    'addParent' : IDL.Func([ParentPayload], [ParentId], []),
    'addStudent' : IDL.Func([StudentPayload], [StudentId], []),
    'addTeacher' : IDL.Func([TeacherPayload], [TeacherId], []),
    'assignRole' : IDL.Func([UserId, Role], [], []),
    'createAnnouncement' : IDL.Func(
        [AnnouncementPayload],
        [AnnouncementId],
        [],
      ),
    'createExam' : IDL.Func([ExamPayload], [ExamId], []),
    'deleteParent' : IDL.Func([ParentId], [IDL.Bool], []),
    'deleteStudent' : IDL.Func([StudentId], [IDL.Bool], []),
    'deleteTeacher' : IDL.Func([TeacherId], [IDL.Bool], []),
    'enterMarks' : IDL.Func([ExamId, IDL.Vec(SubjectMarkEntry)], [IDL.Nat], []),
    'getAttendanceReport' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Text, IDL.Text],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getClassAttendance' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getExam' : IDL.Func([ExamId], [IDL.Opt(ExamView)], ['query']),
    'getMyRole' : IDL.Func([], [IDL.Opt(Role)], ['query']),
    'getParent' : IDL.Func([ParentId], [IDL.Opt(ParentView)], ['query']),
    'getReportCard' : IDL.Func([Id, ExamId], [IDL.Opt(ReportCard)], ['query']),
    'getStudent' : IDL.Func([StudentId], [IDL.Opt(StudentView)], ['query']),
    'getStudentAttendance' : IDL.Func(
        [Id],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getStudentAttendanceStats' : IDL.Func([Id], [AttendanceStats], ['query']),
    'getTeacher' : IDL.Func([TeacherId], [IDL.Opt(TeacherView)], ['query']),
    'isAdminPrincipal' : IDL.Func([UserId], [IDL.Bool], ['query']),
    'listAnnouncements' : IDL.Func([], [IDL.Vec(AnnouncementView)], ['query']),
    'listAnnouncementsByGroup' : IDL.Func(
        [RecipientGroup],
        [IDL.Vec(AnnouncementView)],
        ['query'],
      ),
    'listExams' : IDL.Func([], [IDL.Vec(ExamView)], ['query']),
    'listParents' : IDL.Func([], [IDL.Vec(ParentView)], ['query']),
    'listStudents' : IDL.Func([], [IDL.Vec(StudentView)], ['query']),
    'listTeachers' : IDL.Func([], [IDL.Vec(TeacherView)], ['query']),
    'markAttendance' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(AttendanceEntry)],
        [IDL.Nat],
        [],
      ),
    'registerSelf' : IDL.Func([Role], [], []),
    'searchParents' : IDL.Func([IDL.Text], [IDL.Vec(ParentView)], ['query']),
    'searchStudents' : IDL.Func([IDL.Text], [IDL.Vec(StudentView)], ['query']),
    'searchTeachers' : IDL.Func([IDL.Text], [IDL.Vec(TeacherView)], ['query']),
    'updateParent' : IDL.Func([ParentId, ParentPayload], [IDL.Bool], []),
    'updateStudent' : IDL.Func([StudentId, StudentPayload], [IDL.Bool], []),
    'updateTeacher' : IDL.Func([TeacherId, TeacherPayload], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };