/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface ReportCard {
    studentId: Id;
    subjects: Array<SubjectMarkView>;
    totalObtained: bigint;
    grade: Grade;
    examId: ExamId;
    totalPossible: bigint;
    examName: string;
    percentage: number;
}
export type AttendanceId = bigint;
export interface AnnouncementPayload {
    title: string;
    recipientGroup: RecipientGroup;
    message: string;
}
export interface TeacherView {
    id: TeacherId;
    subjects: Array<string>;
    name: string;
    createdAt: Timestamp;
    contactEmail: string;
    contactPhone: string;
}
export type ParentId = bigint;
export type ExamId = bigint;
export interface SubjectMarkEntry {
    studentId: Id;
    subject: string;
    marksObtained: bigint;
}
export interface TeacherPayload {
    subjects: Array<string>;
    name: string;
    contactEmail: string;
    contactPhone: string;
}
export interface ExamView {
    id: ExamId;
    totalMarks: bigint;
    subjects: Array<string>;
    date: string;
    name: string;
    createdAt: Timestamp;
}
export interface AnnouncementView {
    id: AnnouncementId;
    title: string;
    recipientGroup: RecipientGroup;
    createdAt: Timestamp;
    createdBy: string;
    message: string;
}
export interface StudentPayload {
    name: string;
    rollNumber: string;
    contactEmail: string;
    parentId?: Id;
    className: string;
    contactPhone: string;
}
export interface ParentView {
    id: ParentId;
    name: string;
    createdAt: Timestamp;
    studentIds: Array<Id>;
    contactEmail: string;
    contactPhone: string;
}
export interface AttendanceRecord {
    id: AttendanceId;
    status: AttendanceStatus;
    studentId: Id;
    date: string;
    markedAt: Timestamp;
    className: string;
}
export interface AttendanceEntry {
    status: AttendanceStatus;
    studentId: Id;
}
export interface ExamPayload {
    totalMarks: bigint;
    subjects: Array<string>;
    date: string;
    name: string;
}
export interface ParentPayload {
    name: string;
    studentIds: Array<Id>;
    contactEmail: string;
    contactPhone: string;
}
export interface StudentView {
    id: StudentId;
    name: string;
    createdAt: Timestamp;
    rollNumber: string;
    contactEmail: string;
    parentId?: Id;
    className: string;
    contactPhone: string;
}
export interface SubjectMarkView {
    totalMarks: bigint;
    subject: string;
    marksObtained: bigint;
    grade: Grade;
}
export type StudentId = bigint;
export type TeacherId = bigint;
export interface AttendanceStats {
    studentId: Id;
    presentDays: bigint;
    totalDays: bigint;
    absentDays: bigint;
    presentPercent: number;
}
export type UserId = Principal;
export type Id = bigint;
export type AnnouncementId = bigint;
export enum AttendanceStatus {
    present = "present",
    absent = "absent"
}
export enum Grade {
    a = "a",
    b = "b",
    c = "c",
    d = "d",
    f = "f",
    aPlus = "aPlus",
    cPlus = "cPlus",
    bPlus = "bPlus"
}
export enum RecipientGroup {
    all = "all",
    students = "students",
    teachers = "teachers",
    parents = "parents"
}
export enum Role {
    admin = "admin",
    teacher = "teacher",
    student = "student",
    parent = "parent"
}
export interface backendInterface {
    addParent(payload: ParentPayload): Promise<ParentId>;
    addStudent(payload: StudentPayload): Promise<StudentId>;
    addTeacher(payload: TeacherPayload): Promise<TeacherId>;
    assignRole(target: UserId, role: Role): Promise<void>;
    createAnnouncement(payload: AnnouncementPayload): Promise<AnnouncementId>;
    createExam(payload: ExamPayload): Promise<ExamId>;
    deleteParent(id: ParentId): Promise<boolean>;
    deleteStudent(id: StudentId): Promise<boolean>;
    deleteTeacher(id: TeacherId): Promise<boolean>;
    enterMarks(examId: ExamId, entries: Array<SubjectMarkEntry>): Promise<bigint>;
    getAttendanceReport(className: string | null, fromDate: string, toDate: string): Promise<Array<AttendanceRecord>>;
    getClassAttendance(className: string, date: string): Promise<Array<AttendanceRecord>>;
    getExam(id: ExamId): Promise<ExamView | null>;
    getMyRole(): Promise<Role | null>;
    getParent(id: ParentId): Promise<ParentView | null>;
    getReportCard(studentId: Id, examId: ExamId): Promise<ReportCard | null>;
    getStudent(id: StudentId): Promise<StudentView | null>;
    getStudentAttendance(studentId: Id): Promise<Array<AttendanceRecord>>;
    getStudentAttendanceStats(studentId: Id): Promise<AttendanceStats>;
    getTeacher(id: TeacherId): Promise<TeacherView | null>;
    isAdminPrincipal(principal: UserId): Promise<boolean>;
    listAnnouncements(): Promise<Array<AnnouncementView>>;
    listAnnouncementsByGroup(group: RecipientGroup): Promise<Array<AnnouncementView>>;
    listExams(): Promise<Array<ExamView>>;
    listParents(): Promise<Array<ParentView>>;
    listStudents(): Promise<Array<StudentView>>;
    listTeachers(): Promise<Array<TeacherView>>;
    markAttendance(className: string, date: string, entries: Array<AttendanceEntry>): Promise<bigint>;
    registerSelf(role: Role): Promise<void>;
    searchParents(term: string): Promise<Array<ParentView>>;
    searchStudents(term: string): Promise<Array<StudentView>>;
    searchTeachers(term: string): Promise<Array<TeacherView>>;
    updateParent(id: ParentId, payload: ParentPayload): Promise<boolean>;
    updateStudent(id: StudentId, payload: StudentPayload): Promise<boolean>;
    updateTeacher(id: TeacherId, payload: TeacherPayload): Promise<boolean>;
}
import type { AnnouncementId as _AnnouncementId, AnnouncementPayload as _AnnouncementPayload, AnnouncementView as _AnnouncementView, AttendanceEntry as _AttendanceEntry, AttendanceId as _AttendanceId, AttendanceRecord as _AttendanceRecord, AttendanceStatus as _AttendanceStatus, ExamId as _ExamId, ExamView as _ExamView, Grade as _Grade, Id as _Id, ParentView as _ParentView, RecipientGroup as _RecipientGroup, ReportCard as _ReportCard, Role as _Role, StudentId as _StudentId, StudentPayload as _StudentPayload, StudentView as _StudentView, SubjectMarkView as _SubjectMarkView, TeacherView as _TeacherView, Timestamp as _Timestamp } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addParent(arg0: ParentPayload): Promise<ParentId> {
        if (this.processError) {
            try {
                const result = await this.actor.addParent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addParent(arg0);
            return result;
        }
    }
    async addStudent(arg0: StudentPayload): Promise<StudentId> {
        if (this.processError) {
            try {
                const result = await this.actor.addStudent(to_candid_StudentPayload_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStudent(to_candid_StudentPayload_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addTeacher(arg0: TeacherPayload): Promise<TeacherId> {
        if (this.processError) {
            try {
                const result = await this.actor.addTeacher(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTeacher(arg0);
            return result;
        }
    }
    async assignRole(arg0: UserId, arg1: Role): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignRole(arg0, to_candid_Role_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignRole(arg0, to_candid_Role_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createAnnouncement(arg0: AnnouncementPayload): Promise<AnnouncementId> {
        if (this.processError) {
            try {
                const result = await this.actor.createAnnouncement(to_candid_AnnouncementPayload_n5(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAnnouncement(to_candid_AnnouncementPayload_n5(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createExam(arg0: ExamPayload): Promise<ExamId> {
        if (this.processError) {
            try {
                const result = await this.actor.createExam(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createExam(arg0);
            return result;
        }
    }
    async deleteParent(arg0: ParentId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteParent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteParent(arg0);
            return result;
        }
    }
    async deleteStudent(arg0: StudentId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStudent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStudent(arg0);
            return result;
        }
    }
    async deleteTeacher(arg0: TeacherId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTeacher(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTeacher(arg0);
            return result;
        }
    }
    async enterMarks(arg0: ExamId, arg1: Array<SubjectMarkEntry>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.enterMarks(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.enterMarks(arg0, arg1);
            return result;
        }
    }
    async getAttendanceReport(arg0: string | null, arg1: string, arg2: string): Promise<Array<AttendanceRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAttendanceReport(to_candid_opt_n9(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAttendanceReport(to_candid_opt_n9(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClassAttendance(arg0: string, arg1: string): Promise<Array<AttendanceRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getClassAttendance(arg0, arg1);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClassAttendance(arg0, arg1);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExam(arg0: ExamId): Promise<ExamView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getExam(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExam(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyRole(): Promise<Role | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyRole();
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyRole();
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getParent(arg0: ParentId): Promise<ParentView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getParent(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getParent(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReportCard(arg0: Id, arg1: ExamId): Promise<ReportCard | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getReportCard(arg0, arg1);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReportCard(arg0, arg1);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudent(arg0: StudentId): Promise<StudentView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudent(arg0);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudent(arg0);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudentAttendance(arg0: Id): Promise<Array<AttendanceRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentAttendance(arg0);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentAttendance(arg0);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudentAttendanceStats(arg0: Id): Promise<AttendanceStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentAttendanceStats(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentAttendanceStats(arg0);
            return result;
        }
    }
    async getTeacher(arg0: TeacherId): Promise<TeacherView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeacher(arg0);
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeacher(arg0);
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async isAdminPrincipal(arg0: UserId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdminPrincipal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdminPrincipal(arg0);
            return result;
        }
    }
    async listAnnouncements(): Promise<Array<AnnouncementView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAnnouncements();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAnnouncements();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAnnouncementsByGroup(arg0: RecipientGroup): Promise<Array<AnnouncementView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAnnouncementsByGroup(to_candid_RecipientGroup_n7(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAnnouncementsByGroup(to_candid_RecipientGroup_n7(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async listExams(): Promise<Array<ExamView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listExams();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listExams();
            return result;
        }
    }
    async listParents(): Promise<Array<ParentView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listParents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listParents();
            return result;
        }
    }
    async listStudents(): Promise<Array<StudentView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listStudents();
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listStudents();
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async listTeachers(): Promise<Array<TeacherView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTeachers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTeachers();
            return result;
        }
    }
    async markAttendance(arg0: string, arg1: string, arg2: Array<AttendanceEntry>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.markAttendance(arg0, arg1, to_candid_vec_n39(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAttendance(arg0, arg1, to_candid_vec_n39(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async registerSelf(arg0: Role): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerSelf(to_candid_Role_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerSelf(to_candid_Role_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async searchParents(arg0: string): Promise<Array<ParentView>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchParents(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchParents(arg0);
            return result;
        }
    }
    async searchStudents(arg0: string): Promise<Array<StudentView>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchStudents(arg0);
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchStudents(arg0);
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchTeachers(arg0: string): Promise<Array<TeacherView>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchTeachers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchTeachers(arg0);
            return result;
        }
    }
    async updateParent(arg0: ParentId, arg1: ParentPayload): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateParent(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateParent(arg0, arg1);
            return result;
        }
    }
    async updateStudent(arg0: StudentId, arg1: StudentPayload): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStudent(arg0, to_candid_StudentPayload_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStudent(arg0, to_candid_StudentPayload_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateTeacher(arg0: TeacherId, arg1: TeacherPayload): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTeacher(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTeacher(arg0, arg1);
            return result;
        }
    }
}
function from_candid_AnnouncementView_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AnnouncementView): AnnouncementView {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_AttendanceRecord_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AttendanceRecord): AttendanceRecord {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_AttendanceStatus_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AttendanceStatus): AttendanceStatus {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Grade_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Grade): Grade {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_RecipientGroup_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RecipientGroup): RecipientGroup {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_ReportCard_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReportCard): ReportCard {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_StudentView_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StudentView): StudentView {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_SubjectMarkView_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubjectMarkView): SubjectMarkView {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExamView]): ExamView | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Role]): Role | null {
    return value.length === 0 ? null : from_candid_Role_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ParentView]): ParentView | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ReportCard]): ReportCard | null {
    return value.length === 0 ? null : from_candid_ReportCard_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StudentView]): StudentView | null {
    return value.length === 0 ? null : from_candid_StudentView_n29(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Id]): Id | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TeacherView]): TeacherView | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _AttendanceId;
    status: _AttendanceStatus;
    studentId: _Id;
    date: string;
    markedAt: _Timestamp;
    className: string;
}): {
    id: AttendanceId;
    status: AttendanceStatus;
    studentId: Id;
    date: string;
    markedAt: Timestamp;
    className: string;
} {
    return {
        id: value.id,
        status: from_candid_AttendanceStatus_n13(_uploadFile, _downloadFile, value.status),
        studentId: value.studentId,
        date: value.date,
        markedAt: value.markedAt,
        className: value.className
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    studentId: _Id;
    subjects: Array<_SubjectMarkView>;
    totalObtained: bigint;
    grade: _Grade;
    examId: _ExamId;
    totalPossible: bigint;
    examName: string;
    percentage: number;
}): {
    studentId: Id;
    subjects: Array<SubjectMarkView>;
    totalObtained: bigint;
    grade: Grade;
    examId: ExamId;
    totalPossible: bigint;
    examName: string;
    percentage: number;
} {
    return {
        studentId: value.studentId,
        subjects: from_candid_vec_n23(_uploadFile, _downloadFile, value.subjects),
        totalObtained: value.totalObtained,
        grade: from_candid_Grade_n26(_uploadFile, _downloadFile, value.grade),
        examId: value.examId,
        totalPossible: value.totalPossible,
        examName: value.examName,
        percentage: value.percentage
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalMarks: bigint;
    subject: string;
    marksObtained: bigint;
    grade: _Grade;
}): {
    totalMarks: bigint;
    subject: string;
    marksObtained: bigint;
    grade: Grade;
} {
    return {
        totalMarks: value.totalMarks,
        subject: value.subject,
        marksObtained: value.marksObtained,
        grade: from_candid_Grade_n26(_uploadFile, _downloadFile, value.grade)
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _StudentId;
    name: string;
    createdAt: _Timestamp;
    rollNumber: string;
    contactEmail: string;
    parentId: [] | [_Id];
    className: string;
    contactPhone: string;
}): {
    id: StudentId;
    name: string;
    createdAt: Timestamp;
    rollNumber: string;
    contactEmail: string;
    parentId?: Id;
    className: string;
    contactPhone: string;
} {
    return {
        id: value.id,
        name: value.name,
        createdAt: value.createdAt,
        rollNumber: value.rollNumber,
        contactEmail: value.contactEmail,
        parentId: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.parentId)),
        className: value.className,
        contactPhone: value.contactPhone
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _AnnouncementId;
    title: string;
    recipientGroup: _RecipientGroup;
    createdAt: _Timestamp;
    createdBy: string;
    message: string;
}): {
    id: AnnouncementId;
    title: string;
    recipientGroup: RecipientGroup;
    createdAt: Timestamp;
    createdBy: string;
    message: string;
} {
    return {
        id: value.id,
        title: value.title,
        recipientGroup: from_candid_RecipientGroup_n36(_uploadFile, _downloadFile, value.recipientGroup),
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        message: value.message
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    present: null;
} | {
    absent: null;
}): AttendanceStatus {
    return "present" in value ? AttendanceStatus.present : "absent" in value ? AttendanceStatus.absent : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    teacher: null;
} | {
    student: null;
} | {
    parent: null;
}): Role {
    return "admin" in value ? Role.admin : "teacher" in value ? Role.teacher : "student" in value ? Role.student : "parent" in value ? Role.parent : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    a: null;
} | {
    b: null;
} | {
    c: null;
} | {
    d: null;
} | {
    f: null;
} | {
    aPlus: null;
} | {
    cPlus: null;
} | {
    bPlus: null;
}): Grade {
    return "a" in value ? Grade.a : "b" in value ? Grade.b : "c" in value ? Grade.c : "d" in value ? Grade.d : "f" in value ? Grade.f : "aPlus" in value ? Grade.aPlus : "cPlus" in value ? Grade.cPlus : "bPlus" in value ? Grade.bPlus : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    all: null;
} | {
    students: null;
} | {
    teachers: null;
} | {
    parents: null;
}): RecipientGroup {
    return "all" in value ? RecipientGroup.all : "students" in value ? RecipientGroup.students : "teachers" in value ? RecipientGroup.teachers : "parents" in value ? RecipientGroup.parents : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AttendanceRecord>): Array<AttendanceRecord> {
    return value.map((x)=>from_candid_AttendanceRecord_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SubjectMarkView>): Array<SubjectMarkView> {
    return value.map((x)=>from_candid_SubjectMarkView_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AnnouncementView>): Array<AnnouncementView> {
    return value.map((x)=>from_candid_AnnouncementView_n34(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StudentView>): Array<StudentView> {
    return value.map((x)=>from_candid_StudentView_n29(_uploadFile, _downloadFile, x));
}
function to_candid_AnnouncementPayload_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AnnouncementPayload): _AnnouncementPayload {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_AttendanceEntry_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AttendanceEntry): _AttendanceEntry {
    return to_candid_record_n41(_uploadFile, _downloadFile, value);
}
function to_candid_AttendanceStatus_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AttendanceStatus): _AttendanceStatus {
    return to_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function to_candid_RecipientGroup_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RecipientGroup): _RecipientGroup {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_Role_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): _Role {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_StudentPayload_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StudentPayload): _StudentPayload {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    rollNumber: string;
    contactEmail: string;
    parentId?: Id;
    className: string;
    contactPhone: string;
}): {
    name: string;
    rollNumber: string;
    contactEmail: string;
    parentId: [] | [_Id];
    className: string;
    contactPhone: string;
} {
    return {
        name: value.name,
        rollNumber: value.rollNumber,
        contactEmail: value.contactEmail,
        parentId: value.parentId ? candid_some(value.parentId) : candid_none(),
        className: value.className,
        contactPhone: value.contactPhone
    };
}
function to_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: AttendanceStatus;
    studentId: Id;
}): {
    status: _AttendanceStatus;
    studentId: _Id;
} {
    return {
        status: to_candid_AttendanceStatus_n42(_uploadFile, _downloadFile, value.status),
        studentId: value.studentId
    };
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    recipientGroup: RecipientGroup;
    message: string;
}): {
    title: string;
    recipientGroup: _RecipientGroup;
    message: string;
} {
    return {
        title: value.title,
        recipientGroup: to_candid_RecipientGroup_n7(_uploadFile, _downloadFile, value.recipientGroup),
        message: value.message
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): {
    admin: null;
} | {
    teacher: null;
} | {
    student: null;
} | {
    parent: null;
} {
    return value == Role.admin ? {
        admin: null
    } : value == Role.teacher ? {
        teacher: null
    } : value == Role.student ? {
        student: null
    } : value == Role.parent ? {
        parent: null
    } : value;
}
function to_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AttendanceStatus): {
    present: null;
} | {
    absent: null;
} {
    return value == AttendanceStatus.present ? {
        present: null
    } : value == AttendanceStatus.absent ? {
        absent: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RecipientGroup): {
    all: null;
} | {
    students: null;
} | {
    teachers: null;
} | {
    parents: null;
} {
    return value == RecipientGroup.all ? {
        all: null
    } : value == RecipientGroup.students ? {
        students: null
    } : value == RecipientGroup.teachers ? {
        teachers: null
    } : value == RecipientGroup.parents ? {
        parents: null
    } : value;
}
function to_candid_vec_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<AttendanceEntry>): Array<_AttendanceEntry> {
    return value.map((x)=>to_candid_AttendanceEntry_n40(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
